spring.application.name=OpenBankingApp
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.scope=openid, profile, email
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=sub

#spring.security.oauth2.client.registration.paymentsnz.client-id=3208827295154ebeab4f0b24c3332105
#spring.security.oauth2.client.registration.paymentsnz.client-secret=YOUR_CLIENT_SECRET
#spring.security.oauth2.client.registration.paymentsnz.scope=openid,profile,email
#spring.security.oauth2.client.registration.paymentsnz.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.paymentsnz.client-name=PaymentsNZ
#spring.security.oauth2.client.registration.paymentsnz.authorization-grant-type=authorization_code
#
#spring.security.oauth2.client.provider.paymentsnz.authorization-uri=https://sandbox.api.paymentsnz.io/oidc/authorize
#spring.security.oauth2.client.provider.paymentsnz.token-uri=https://sandbox.api.paymentsnz.io/oidc/token
#spring.security.oauth2.client.provider.paymentsnz.user-info-uri=https://sandbox.api.paymentsnz.io/oidc/userinfo
#spring.security.oauth2.client.provider.paymentsnz.jwk-set-uri=https://sandbox.api.paymentsnz.io/oidc/jwks
#spring.security.oauth2.client.provider.paymentsnz.user-name-attribute=sub

paymentsnz.client-id=3208827295154ebeab4f0b24c3332105
paymentsnz.token-url=https://api-nomatls.apicentre.middleware.co.nz/oauth/v2.0/token
paymentsnz.private-key-path=src/main/resources/private_key.pem
paymentsnz.issuer=3208827295154ebeab4f0b24c3332105
paymentsnz.audience=https://api-nomatls.apicentre.middleware.co.nz/oauth/v2.0/token